apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-secret
  namespace: velotio-ak
spec:
  selector:
    matchLabels:
      run: busybox-sec
  template:
    metadata:
      labels:
        run: busybox-sec
        app: velotio
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: velotio-secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: velotio-secret
                key: password
        