apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-cm
  namespace: velotio-ak
spec:
  selector:
    matchLabels:
      run: busybox
  template:
    metadata:
      labels:
        run: busybox
        app: velotio
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
        env:
          - name: cm-usage
            valueFrom:
              configMapKeyRef:
                name: velotio-cm
                key: env1
status: {}
