
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-security-context
  namespace: velotio-ak
spec:

  selector:
    matchLabels:
      run: busybox
  template:
    metadata:
      labels:
        run: busybox
        app: velotio
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - image: busybox
        name: busybox
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
